### ISSUE TITLE
pupil_preprocess_python interpolation issue

### ISSUE THREAD

**Issue by recoveringMathmo** [tknapen/FIRDeconvolution#3]
Hi, I'm just working through your example of preprocessing pupil data and there's a slight problem with the interpolation section. I have fixed it with the following

```
margin = 100 # ms
margin = int((margin*sample_rate)/1000) # number of TS
pupil_interpolated = np.array(pupil.copy())
for b in range(len(blink_starts)):
    blink_start = blink_starts[b] 
    blink_end = blink_ends[b] 
    blink_start =  np.where(timepoints==blink_start)[0][0] - margin
    blink_end =  np.where(timepoints==blink_end)[0][0] + margin
    interpolated_signal = np.linspace(pupil_interpolated[blink_start], 
                                      pupil_interpolated[blink_end],
                                      blink_end-blink_start)
    pupil_interpolated[blink_start:blink_end] = interpolated_signal

f = pl.figure(figsize = (10,3.5))
pl.plot(x, pupil_interpolated)
pl.xlabel('Time (s)')
pl.ylabel('Pupil size')
sn.despine(offset=10)
```

Basically if you change the sampling rate then you don't interpolate the correct part of the sequence, it was just lucky that the sampling rate in the example was 1000. 

I'm probably going to be working on this code for a little bit, do you want me to fork and make changes or submit issues as and when?

Cheers

**Comment by recoveringMathmo** [comment]
That code I posted isn't quite right either! Sorry, premature issue creation. I'll go back and edit it once I've fixed it.

**Comment by tknapen** [comment]
No problem, keep me posted !

Tomas

**Comment by recoveringMathmo** [comment]
Ok so not sure it's an issue, but unexpected behaviour from the test. The blink start timestamp shown in the blink dictionary is the second blink point recorded, similarly the end timestamp is the penultimate blinked point in your data. This might explain some of the problems I was getting using a zero margin.
