### ISSUE TITLE
Saccadic regressor

### ISSUE THREAD

**Issue by recoveringMathmo** [tknapen/FIRDeconvolution#5]
Me again,

I've made some more changes to the example in your code to make it compatible with alternative sampling rates. I think I've finished, but I've noticed something that looks like a mistake to me but wanted to check.

```
blink_reg = np.zeros(len(pupil))
blink_reg[blink_ends] = 1
blink_reg_conv = sp.signal.fftconvolve(blink_reg, blink_kernel, 'full')[:-(len(blink_kernel)-1)]
sac_reg = np.zeros(len(pupil))
sac_reg[blink_ends] = 1
sac_reg_conv = sp.signal.fftconvolve(sac_reg, sac_kernel, 'full')[:-(len(sac_kernel)-1)]
regs = [blink_reg_conv, sac_reg_conv]
```

I think that 
`sac_reg[blink_ends] = 1`
Should be
`sac_reg[sac_ends] = 1`

Does that seem correct to you? 

Sorry for spamming you, I'm a bit of a novice at signal processing.

**Comment by tknapen** [comment]
I'm pretty sure you're right! Thanks for this! I'll soon have the time to work through the whole package again in order to fix these things ...
